### PR TITLE
Login to expo before eject

### LINKED ISSUE #14: post-compilation simple expo 0.40.0 app crash on android "expo-updates must be configured with a valid update URL or scope key"
### Troubleshooting

- [x] I've searched [discuss.bitrise.io](https://discuss.bitrise.io/) for possible solutions.
- Which version of the step is effected? _1.0.0_
- Is the issue reproducible with the latest version? _YES _
- Does the issue happen sporadically, or every time? _ EVERY TIME_
- Is the issue reproducible locally by following our [local debug guide](NO)? _ NO _

### Useful information

- [FAQ](https://devcenter.bitrise.io/faq/faq-index/)
- [devcenter.bitrise.io](https://devcenter.bitrise.io/)

### Issue description

When building on btirise ,  this steps does not generate a EXPO_UPDATE_URL in the manifest of android
which cause the app to crash at runtime with the following error in `logcat`
```
expo-updates must be configured with a valid update URL or scope key
```

analyzing the produce apk confirm this hypothesis (no EXPO_UPDATE_URL in manifest) 

however when building locally with bitrise cli,  this variable is present, and the apk is then able to launch the app correctly 

### Bitrise info

- Build URL: https://app.bitrise.io/build/7412ee4d68eaeffc#?tab=log
- [Bitrise Support](https://devcenter.bitrise.io/troubleshooting/enabling-bitrise-support-user/) enabled: _YES_
- Log: 

<details>
  <pre>
 
  </pre>
</details>

### Steps to reproduce

Create a managed app with expo-cli , for sdk 40 of expo, nothing more 

1. ...
2. ...

### PR DESCRIPTION
**Pull request by adborbas**
### Checklist

- [x] I've read and accepted the [Contribution Guidelines](https://github.com/bitrise-steplib/.github/blob/main/CONTRIBUTING.md)
- Requires MINOR [version update](https://semver.org/)

### Context

Some expo modules require `expo login` to be run before ejecting. If both `user_name` and `password` is provided we will 
run `expo login` to support this.

Resolves: #14 
Resolves: [STEP-594](https://bitrise.atlassian.net/browse/STEP-594)

### Changes

- Run `expo login` when `user_name` and `password` is provided.
- Run `expo logout` at the end of the step or when the step fails.
- Extend e2e test to validate that expo.modules.updates.EXPO_UPDATE_URL is present in AndroidManifest.xml.
- Update `step.yml`

### CODE REVIEW

File: main.go [hunk 1]
```diff
@@ -100,17 +118,16 @@ func main() {
 	log.Infof("Eject project")
 	{
 		if err := e.eject(); err != nil {
-			failf("Failed to eject project: %s", err)
+			failfDefered(func() { logout(e) }, "Failed to eject project: %s", err)
```
Comment (lpusok) [inline main.go]: I would recommend creating a "main2" function which returns errors and it is called from main. This would prevent the need for isLoggedIn and failedDefered as the "defer logout(e)" would called when the function returns.

Comment (adborbas) [reply main.go]: That is a great idea 👍

**Review by lpusok — APPROVED** [review]

**Review by mateherber — APPROVED** [review]
