### PR TITLE
[STEP-10]: Remove expo cli eject method

### LINKED ISSUE #12: error: unknown option `--eject-method'
The latest release of `expo-cli` removes the `--eject-method` option, which causes this step to fail.

According to NPM, the breaking change was pushed on (or around) Oct 14, 2020.  Quick fix is to explicitly set the `expo-cli` version to 3.27.14, which is the latest version of the package that supports this flag.

### PR DESCRIPTION
**Pull request by adborbas**
Should fix #12 and #7.

**Description**
Updating the step to reflect the changes in expo cli made to the `eject` command. `expo cli` no longer support using the `--eject-method` parameter.

**Changes:**

- Removed `[Beta]` tag from `step.yml` title and README.md.
- Removed unsupported `--eject-method`.
- Update the [sample app](https://github.com/bitrise-io/react-native-expo) to use [SDK39](https://github.com/bitrise-io/react-native-expo/tree/SDK39).
- Extracted `Expo` struct to a separate `expo.go` file.
- `bitrise.yml`
  - removed `expo_kit ` workflow as expoKit is no longer supported.
  - renamed `bare` workflow to `eject`
  - file has a lot of format changes
- Updated `step.yml`

### CODE REVIEW

**Review by istvankovacs-bitrise — DISMISSED** [review]
As far as I understand the context, it looks good to me!

File: main.go [hunk 1]
```diff
@@ -298,3 +157,35 @@ func main() {
...
+			}
+		}
+	}()
+
+	fmt.Println()
+	log.Infof("Running expo publish")
+
+	// Running publish
+	if err := expo.publish(); err != nil {
+		failf("Failed to publish project: %s", err)
```
Comment (lpusok) [inline main.go]: Please return error instead of failf in a function other than main.

File: expo.go [hunk 2]
```diff
@@ -0,0 +1,87 @@
...
+		args = append(args, "expo-cli@"+e.Version)
+	} else {
+		args = append(args, "expo-cli")
+	}
+
+	cmd := command.New("npm", args...)
+	cmd.SetStdout(os.Stdout)
+	cmd.SetStderr(os.Stderr)
+
+	log.Donef("$ " + cmd.PrintableCommandArgs())
```
Comment (lpusok) [inline expo.go]: NOTE: It is better to use log.Donef("$ %s", cmd.PrintableCommandArgs()), in case there are special characters that are not quoted (like %)

File: expo.go [hunk 3]
```diff
@@ -0,0 +1,87 @@
...
+	return cmd.Run()
+}
+
+// Logout from your Expo account
+func (e Expo) logout() error {
+	cmd := command.New("expo", "logout", "--non-interactive")
+	cmd.SetStdout(os.Stdout)
+	cmd.SetStderr(os.Stderr)
+
+	log.Printf("$ " + cmd.PrintableCommandArgs())
```
Comment (lpusok) [inline expo.go]: NOTE: it could be log.Donef for consistency.

**Review by lpusok — CHANGES_REQUESTED** [review]

File: README.md [hunk 4]
```diff
@@ -1,4 +1,4 @@
-# [Beta] Expo Eject
+# Expo Eject
 
 Using the The Expo Development CLI to Creates Xcode and Android Studio projects for your app.
```
Comment (BanyikAnna) [inline README.md]: Use the Expo Development CLI to create Xcode and Android Studio projects for your app.

File: bitrise.yml [hunk 5]
```diff
@@ -3,115 +3,89 @@ default_step_lib_source: https://github.com/bitrise-io/bitrise-steplib.git
...
-        - project_path: $BITRISE_SOURCE_DIR
-        - expo_cli_verson: "latest"
-        - user_name: $USER_NAME
-        - password: $PASSWORD
+      - script:
+          title: Clone sample app
+          inputs:
+            - content: git clone $SAMPLE_APP_URL . -b $BRANCH && cd
+      - npm@0.9.1:
+          title: Install node modules for the expo project
```
Comment (BanyikAnna) [inline bitrise.yml]: expo project > Expo project (as in their official documentation) ;)

File: bitrise.yml [hunk 6]
```diff
@@ -3,115 +3,89 @@ default_step_lib_source: https://github.com/bitrise-io/bitrise-steplib.git
...
+            - content: |-
+                #!/bin/bash
+                set -ex
+                cd ${ORIGIN_SOURCE_DIR}
+                rm -rf "./_tmp"
+                mkdir "_tmp"
+      - change-workdir:
+          title: Switch working dir to test / _tmp dir
+          description: |-
+            To prevent step testing issues, like referencing relative
```
Comment (BanyikAnna) [inline bitrise.yml]: step > Step

File: bitrise.yml [hunk 7]
```diff
@@ -3,115 +3,89 @@ default_step_lib_source: https://github.com/bitrise-io/bitrise-steplib.git
...
+            files with just './some-file' in the step's code, which would
```
Comment (BanyikAnna) [inline bitrise.yml]: step's code > Step's code

File: bitrise.yml [hunk 8]
```diff
@@ -3,115 +3,89 @@ default_step_lib_source: https://github.com/bitrise-io/bitrise-steplib.git
...
+            but would break if the step is included in another `bitrise.yml`.
+          run_if: true
+          inputs:
+            - path: ${ORIGIN_SOURCE_DIR}/_tmp
+            - is_create_path: true
 
   dep-update:
     title: Dep update
     description: |
       Used for updating bitrise dependencies with dep
```
Comment (BanyikAnna) [inline bitrise.yml:70]: Used for updating bitrise dependencies with dep > Update Bitrise dependencies with dep.

File: step.yml [hunk 9]
```diff
@@ -101,18 +88,10 @@ inputs:
...
-        In case of React Native project using Expo Kit library (any .js file imports expo),  
-        `expo publis` command generates the:
-
-        - ./android/app/src/main/assets/shell-app-manifest.json
-        - ./android/app/src/main/assets/shell-app.bundle
-        - ./ios/bitriseexpokit/Supporting/shell-app-manifest.json
-        - ./ios/bitriseexpokit/Supporting/shell-app.bundle
-
-        files, which are required for the native builds.
+        If set to "yes" both `user_name` and `password` are required to be provided.
```
Comment (BanyikAnna) [inline step.yml]: If set to "yes", both ....

File: expo.go (hunk 2 above)
Comment (adborbas) [reply expo.go]: Wow, nice catch 👍 .

File: bitrise.yml (hunk 8 above)
Comment (adborbas) [reply bitrise.yml:70]: As discussed over Slack this is not user facing.

File: main.go [hunk 10]
```diff
@@ -158,14 +160,14 @@ func main() {
...
-func runPublish(expo Expo, cfg Config) {
+func runPublish(expo Expo, cfg Config) error {
 	//
 	// Logging in the user to the Expo account
 	fmt.Println()
 	log.Infof("Login to Expo")
 	{
 		if err := expo.login(cfg.UserName, cfg.Password); err != nil {
-			failf("Failed to log in to your provided Expo account, error: %s", err)
+			return fmt.Errorf("failed to log in to your provided Expo account, error: %s", err)
```
Comment (lpusok) [inline main.go]: One small thing: it is not best practice anymore to use ", error:" you can just leave the error out.

**Review by lpusok — APPROVED** [review]
